version: '3.3'
services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    build: ./redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - app