version: '3.3'
services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    build: ./redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - app